name: EAS Build and Release

on:
  push:
    tags:
      - 'v0.*.*'
      - 'v0.*.*-*'

jobs:
  build_and_release:
    name: Build and Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build on EAS
        run: |
          eas build --platform android --profile production --non-interactive --json > build.json
          APK_URL=$(jq -r '.[0].artifacts.buildUrl' build.json)
          wget -O app.apk $APK_URL

      - name: Extract Tag Information for Description
        id: extract_desc
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          if [[ "$TAG_NAME" == *-* ]]; then
            DESC="${TAG_NAME#*-}"
            DESC="${DESC//-/ }"
            echo "desc=$DESC" >> $GITHUB_OUTPUT
          else
            echo "desc=Automated release for $TAG_NAME" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: app.apk
          name: ${{ github.ref_name }}
          body: ${{ steps.extract_desc.outputs.desc }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
